import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Loader from '../components/Loader'

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
            <ClerkLoading>
              <div className="h-screen flex items-center justify-center w-full">
              <Loader/>            

              </div>
            </ClerkLoading>
            <ClerkLoaded>

              {children}
            </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
